openapi: 3.0.0
info:
  title: Argent Bank API
  description: API documentation for Argent Bank
  version: 1.0.0
servers:
  - url: http://localhost:3001/api/v1
paths:
  /user/signup:
    post:
      tags:
        - User
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                password:
                  type: string
                userName:
                  type: string
      responses:
        "200":
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  message:
                    type: string
                  body:
                    $ref: "#/components/schemas/User"
        "400":
          description: Invalid fields
        "500":
          description: Internal server error
  /user/login:
    post:
      tags:
        - User
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  message:
                    type: string
                  body:
                    type: object
                    properties:
                      token:
                        type: string
        "400":
          description: Invalid fields
        "500":
          description: Internal server error
  /user/profile:
    get:
      tags:
        - User
      summary: Get user profile
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer JWT token
      responses:
        "200":
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  message:
                    type: string
                  body:
                    $ref: "#/components/schemas/User"
        "400":
          description: Invalid fields
        "500":
          description: Internal server error
    put:
      tags:
        - User
      summary: Update user profile
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                userName:
                  type: string
      responses:
        "200":
          description: User profile updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  message:
                    type: string
                  body:
                    $ref: "#/components/schemas/User"
        "400":
          description: Invalid fields
        "500":
          description: Internal server error
  /transactions/{accountId}:
    get:
      tags:
        - Transaction
      summary: Get transactions for the current month of a specific account
      description: Get transactions for the current month of the user in function of access token in header request
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer JWT token
        - name: accountId
          in: path
          required: true
          schema:
            type: string
            description: ID of the account to return transactions
      responses:
        "200":
          description: User transactions retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  message:
                    type: string
                  body:
                    type: array
                    items:
                      $ref: "#/components/schemas/Transaction"
        "400":
          description: Invalid fields
        "500":
          description: Internal server error
  /transaction/{transactionId}:
    get:
      tags:
        - Transaction
      summary: Get details of a specific transaction
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer JWT token
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
            description: ID of the transaction to return details
      responses:
        "200":
          description: Transaction details retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  message:
                    type: string
                  body:
                    $ref: "#/components/schemas/Transaction"
        "400":
          description: Invalid fields
        "500":
          description: Internal server error
    put:
      tags:
        - Transaction
      summary: Update category and notes of a specific transaction
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer JWT token
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
            description: ID of the transaction to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                notes:
                  type: string
      responses:
        "200":
          description: Transaction updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                  message:
                    type: string
                  body:
                    $ref: "#/components/schemas/Transaction"
        "400":
          description: Invalid fields
        "500":
          description: Internal server error

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        userName:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
    Transaction:
      type: object
      properties:
        id:
          type: string
        date:
          type: string
        description:
          type: string
        category:
          type: string
        balance:
          type: number
        amount:
          type: number
        type:
          type: string
        notes:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              note:
                type: string
